/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Screens;

import Controllers.PatientController;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Denu
 */
public class AddPatient extends javax.swing.JInternalFrame {

    PatientController controller = new PatientController();
    /**
     * Creates new form AddPatient
     */
    public AddPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private String setGender () {
        if (radioMan.isSelected()){
            return "M";
        }
        
        return "F";
        
    };
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addPatientSubmit = new javax.swing.JButton();
        addPatientCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientHistory = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        patientId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        radioMan = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        patientLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Name");

        addPatientSubmit.setBackground(new java.awt.Color(0, 153, 51));
        addPatientSubmit.setText("Add");
        addPatientSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientSubmitActionPerformed(evt);
            }
        });

        addPatientCancel.setBackground(new java.awt.Color(153, 0, 0));
        addPatientCancel.setText("Cancel");
        addPatientCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientCancelActionPerformed(evt);
            }
        });

        patientHistory.setColumns(20);
        patientHistory.setRows(5);
        jScrollPane1.setViewportView(patientHistory);

        jLabel2.setText("Medic History");

        jLabel4.setText("ID");

        radioMan.setText("Man");

        radioFemale.setText("Female");

        jLabel3.setText("Lastname");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(patientId)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(patientName)
                    .addComponent(addPatientSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(addPatientCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioMan)
                        .addGap(32, 32, 32)
                        .addComponent(radioFemale))
                    .addComponent(patientLastname))
                .addContainerGap(649, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(patientLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMan)
                    .addComponent(radioFemale))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(addPatientSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPatientCancel)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientSubmitActionPerformed
        String gender = setGender();
        
        try {
            controller.addPatient(patientId.getText(), patientName.getText(), patientLastname.getText(), patientHistory.getText(), gender);
            JOptionPane.showMessageDialog(null, "The patient has been registered succesfully");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Couldn't add new Patient: " + ex);
        }
        
        
    }//GEN-LAST:event_addPatientSubmitActionPerformed

    private void addPatientCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_addPatientCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientCancel;
    private javax.swing.JButton addPatientSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea patientHistory;
    private javax.swing.JTextField patientId;
    private javax.swing.JTextField patientLastname;
    private javax.swing.JTextField patientName;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMan;
    // End of variables declaration//GEN-END:variables
}
